# Poststack Environment Configuration for Unified Project
# This file defines multi-environment deployment settings
environment: dev  # Currently selected environment

project:
  name: unified
  description: "Unified project with Apache web server and PostgreSQL database"

environments:
  # Development environment - for local development
  dev:
    deployments:
      - name: postgres
        type: postgres
        pod: containers/postgres/postgres-pod.yaml
        variables:
          DB_NAME: unified_dev
          DB_PORT: "5436"
          DB_USER: unified_dev_user
          DB_PASSWORD: "dev_password123"
      - name: apache
        type: web
        pod: containers/apache/apache-pod.yaml
        depends_on: [postgres]
        variables:
          # Apache-specific variables
          SERVER_NAME: dev.unified.local
          SERVER_ADMIN: dev@unified.local
          APACHE_LOG_LEVEL: debug
    init: []  # No init containers needed for dev
    volumes:
      postgres_data:
        type: named
        size: "2Gi"
      postgres_logs:
        type: named
        size: "500Mi"
      postgres_config:
        type: emptyDir
      apache_logs:
        type: named
        size: "1Gi"
      apache_config:
        type: emptyDir
      dovecot_mail:
        type: named
        size: "500Mi"
      dovecot_logs:
        type: named
        size: "100Mi"
      dovecot_config:
        type: emptyDir
    variables:
      LOG_LEVEL: debug
      DEBUG_MODE: "true"
      CACHE_TTL: "60"
      APACHE_HOST_PORT: "8080"
      APACHE_HTTPS_PORT: "8443"
      APP_VERSION: "dev-latest"
      POSTSTACK_ENVIRONMENT: dev

  # Staging environment - for testing before production
  staging:
    deployments:
      - name: postgres
        type: postgres
        pod: containers/postgres/postgres-pod.yaml
        variables:
          DB_NAME: unified_staging
          DB_PORT: "5434"
          DB_USER: unified_staging_user
          DB_PASSWORD: "dev_password123"
      - name: apache
        type: web
        pod: containers/apache/apache-pod.yaml
        depends_on: [postgres]
        variables:
          SERVER_NAME: staging.unified.local
          SERVER_ADMIN: staging@unified.local
          APACHE_LOG_LEVEL: info
    init: []  # Could add migration containers here in the future
    variables:
      LOG_LEVEL: info
      DEBUG_MODE: "false"
      CACHE_TTL: "300"
      APACHE_HOST_PORT: "8081"
      APACHE_HTTPS_PORT: "8444"
      SERVER_NAME: "staging.unified.local"
      SERVER_ADMIN: "staging@unified.local"
      APACHE_LOG_LEVEL: "info"
      APP_VERSION: "staging-0.1.0"

  # Production environment - for live deployment
  production:
    deployments:
      - name: postgres
        type: postgres
        pod: containers/postgres/postgres-pod.yaml
        variables:
          DB_NAME: unified_prod
          DB_PORT: "5435"
          DB_USER: unified_prod_user
          DB_PASSWORD: "dev_password123"
      - name: apache
        type: web
        pod: containers/apache/apache-pod.yaml
        depends_on: [postgres]
        variables:
          SERVER_NAME: unified.example.com
          SERVER_ADMIN: admin@unified.example.com
          APACHE_LOG_LEVEL: warn
    init: []  # Would typically have migrations and data seeding
    variables:
      LOG_LEVEL: warn
      DEBUG_MODE: "false"
      CACHE_TTL: "3600"
      APACHE_HOST_PORT: "80"
      APACHE_HTTPS_PORT: "443"
      SERVER_NAME: "unified.example.com"
      SERVER_ADMIN: "admin@unified.example.com"
      APACHE_LOG_LEVEL: "warn"
      APP_VERSION: "1.0.0"
