# Poststack Environment Configuration for Unified Project
# This file defines multi-environment deployment settings
environment: dev  # Currently selected environment

project:
  name: unified
  description: "Unified project with Apache web server and PostgreSQL database"

environments:
  # Development environment - for local development
  dev:
    postgres:
      database: unified_dev
      port: 5436
      user: unified_dev_user
      password: auto_generated
      host: host.containers.internal
    init: []  # No init containers needed for dev
    deployment:
      pod: deploy/apache-pod.yaml
    volumes:
      postgres_data:
        type: named
        size: "2Gi"
      postgres_logs:
        type: named
        size: "500Mi"
      postgres_config:
        type: emptyDir
      apache_logs:
        type: named
        size: "1Gi"
      apache_config:
        type: emptyDir
    variables:
      LOG_LEVEL: debug
      DEBUG_MODE: "true"
      CACHE_TTL: "60"
      APACHE_HOST_PORT: "8080"
      APACHE_HTTPS_PORT: "8443"
      SERVER_NAME: "dev.unified.local"
      SERVER_ADMIN: "dev@unified.local"
      APACHE_LOG_LEVEL: "debug"
      APP_VERSION: "dev-latest"

  # Staging environment - for testing before production
  staging:
    postgres:
      database: unified_staging
      port: 5434
      user: unified_staging_user
      password: auto_generated
      host: localhost
    init: []  # Could add migration containers here in the future
    deployment:
      pod: deploy/apache-pod.yaml
    variables:
      LOG_LEVEL: info
      DEBUG_MODE: "false"
      CACHE_TTL: "300"
      APACHE_HOST_PORT: "8081"
      APACHE_HTTPS_PORT: "8444"
      SERVER_NAME: "staging.unified.local"
      SERVER_ADMIN: "staging@unified.local"
      APACHE_LOG_LEVEL: "info"
      APP_VERSION: "staging-0.1.0"

  # Production environment - for live deployment
  production:
    postgres:
      database: unified_prod
      port: 5435
      user: unified_prod_user
      password: auto_generated
      host: localhost
    init: []  # Would typically have migrations and data seeding
    deployment:
      pod: deploy/apache-pod.yaml
    variables:
      LOG_LEVEL: warn
      DEBUG_MODE: "false"
      CACHE_TTL: "3600"
      APACHE_HOST_PORT: "80"
      APACHE_HTTPS_PORT: "443"
      SERVER_NAME: "unified.example.com"
      SERVER_ADMIN: "admin@unified.example.com"
      APACHE_LOG_LEVEL: "warn"
      APP_VERSION: "1.0.0"
