# Poststack Environment Configuration for Unified Project
# This file defines multi-environment deployment settings
environment: dev  # Currently selected environment

project:
  name: unified
  description: "Unified project with Apache web server and PostgreSQL database"

environments:
  # Development environment - for local development
  dev:
    deployments:
      - name: volume-setup
        type: init
        pod: containers/volume-setup/volume-setup-pod.yaml.j2
        variables:
          INIT_TYPE: volume-setup
      - name: postgres
        type: postgres
        pod: containers/postgres/postgres-pod.yaml.j2
        depends_on: [volume-setup]
        variables:
          DB_NAME: unified_dev
          DB_PORT: "5436"
          DB_USER: unified_dev_user
          DB_PASSWORD: "dev_password123"
      - name: apache
        type: web
        pod: containers/apache/apache-pod.yaml.j2
        depends_on: [postgres, volume-setup]
        variables:
          # Apache-specific variables
          SERVER_NAME: lab.sethlakowske.com
          SERVER_ADMIN: lakowske@gmail.com
          APACHE_LOG_LEVEL: debug
          # SSL configuration
          SSL_ENABLED: "true"
          SSL_REDIRECT: "false"
          # Network configuration
          APACHE_USE_HOST_NETWORK: "true"
      - name: mail
        type: mail
        pod: containers/mail/mail-pod.yaml.j2
        depends_on: [postgres, volume-setup]
        variables:
          # Mail-specific variables
          MAIL_DOMAIN: lab.sethlakowske.com
          MAIL_LOG_LEVEL: debug
          MAIL_SMTP_PORT: "2525"
          MAIL_IMAP_PORT: "1144"
      - name: fail2ban
        type: fail2ban
        pod: containers/fail2ban/fail2ban-pod.yaml.j2
        depends_on: [apache, mail]
        variables:
          # Fail2ban-specific variables
          FAIL2BAN_LOG_LEVEL: INFO
          FAIL2BAN_BANTIME: "3600"
          FAIL2BAN_FINDTIME: "600"
          FAIL2BAN_MAXRETRY: "5"
    init: []
    volumes:
      postgres_data:
        type: named
      postgres_config:
        type: emptyDir
      apache_config:
        type: emptyDir
      mail_data:
        type: named
      mail_config:
        type: emptyDir
      unified_logs:
        type: named
      fail2ban_data:
        type: named
      fail2ban_config:
        type: emptyDir
      certificates:
        type: named
    variables:
      LOG_LEVEL: debug
      DEBUG_MODE: "true"
      CACHE_TTL: "60"
      APACHE_HOST_PORT: "8080"
      APACHE_HTTPS_PORT: "8443"
      APP_VERSION: "dev-latest"
      POSTSTACK_ENVIRONMENT: dev
      # Network mode configuration (host for dev environment)
      NETWORK_MODE: "host"
      MAIL_USE_HOST_NETWORK: "true"
      APACHE_USE_HOST_NETWORK: "true"

  # Staging environment - for testing before production
  staging:
    deployments:
      - name: volume-setup
        type: init
        pod: containers/volume-setup/volume-setup-pod.yaml.j2
        variables:
          INIT_TYPE: volume-setup
      - name: postgres
        type: postgres
        pod: containers/postgres/postgres-pod.yaml.j2
        depends_on: [volume-setup]
        variables:
          DB_NAME: unified_staging
          DB_PORT: "5434"
          DB_USER: unified_staging_user
          DB_PASSWORD: "dev_password123"
      - name: apache
        type: web
        pod: containers/apache/apache-pod.yaml.j2
        depends_on: [postgres, volume-setup]
        variables:
          SERVER_NAME: staging.unified.local
          SERVER_ADMIN: staging@unified.local
          APACHE_LOG_LEVEL: info
      - name: mail
        type: mail
        pod: containers/mail/mail-pod.yaml.j2
        depends_on: [postgres, volume-setup]
        variables:
          # Mail-specific variables
          MAIL_DOMAIN: staging.unified.local
          MAIL_LOG_LEVEL: info
          MAIL_SMTP_PORT: "2525"
          MAIL_IMAP_PORT: "1144"
      - name: fail2ban
        type: fail2ban
        pod: containers/fail2ban/fail2ban-pod.yaml.j2
        depends_on: [apache, mail]
        variables:
          # Fail2ban-specific variables
          FAIL2BAN_LOG_LEVEL: INFO
          FAIL2BAN_BANTIME: "7200"
          FAIL2BAN_FINDTIME: "600"
          FAIL2BAN_MAXRETRY: "3"
    init: []
    volumes:
      postgres_data:
        type: named
      postgres_config:
        type: emptyDir
      apache_config:
        type: emptyDir
      mail_data:
        type: named
      mail_config:
        type: emptyDir
      unified_logs:
        type: named
      fail2ban_data:
        type: named
      fail2ban_config:
        type: emptyDir
      certificates:
        type: named
    variables:
      LOG_LEVEL: info
      DEBUG_MODE: "false"
      CACHE_TTL: "300"
      APACHE_HOST_PORT: "8081"
      APACHE_HTTPS_PORT: "8444"
      SERVER_NAME: "staging.unified.local"
      SERVER_ADMIN: "staging@unified.local"
      APACHE_LOG_LEVEL: "info"
      APP_VERSION: "staging-0.1.0"
      POSTSTACK_ENVIRONMENT: staging
      # Network mode configuration (host for staging environment - for fail2ban)
      NETWORK_MODE: "host"
      MAIL_USE_HOST_NETWORK: "true"
      APACHE_USE_HOST_NETWORK: "true"

  # Production environment - for live deployment
  production:
    deployments:
      - name: volume-setup
        type: init
        pod: containers/volume-setup/volume-setup-pod.yaml.j2
        variables:
          INIT_TYPE: volume-setup
      - name: postgres
        type: postgres
        pod: containers/postgres/postgres-pod.yaml.j2
        depends_on: [volume-setup]
        variables:
          DB_NAME: unified_prod
          DB_PORT: "5435"
          DB_USER: unified_prod_user
          DB_PASSWORD: "dev_password123"
      - name: apache
        type: web
        pod: containers/apache/apache-pod.yaml.j2
        depends_on: [postgres, volume-setup]
        variables:
          SERVER_NAME: unified.example.com
          SERVER_ADMIN: admin@unified.example.com
          APACHE_LOG_LEVEL: warn
      - name: mail
        type: mail
        pod: containers/mail/mail-pod.yaml.j2
        depends_on: [postgres, volume-setup]
        variables:
          # Mail-specific variables
          MAIL_DOMAIN: unified.example.com
          MAIL_LOG_LEVEL: warn
          MAIL_SMTP_PORT: "25"
          MAIL_IMAP_PORT: "143"
      - name: fail2ban
        type: fail2ban
        pod: containers/fail2ban/fail2ban-pod.yaml.j2
        depends_on: [apache, mail]
        variables:
          # Fail2ban-specific variables
          FAIL2BAN_LOG_LEVEL: WARN
          FAIL2BAN_BANTIME: "86400"
          FAIL2BAN_FINDTIME: "3600"
          FAIL2BAN_MAXRETRY: "3"
    init: []
    volumes:
      postgres_data:
        type: named
      postgres_config:
        type: emptyDir
      apache_config:
        type: emptyDir
      mail_data:
        type: named
      mail_config:
        type: emptyDir
      unified_logs:
        type: named
      fail2ban_data:
        type: named
      fail2ban_config:
        type: emptyDir
      certificates:
        type: named
    variables:
      LOG_LEVEL: warn
      DEBUG_MODE: "false"
      CACHE_TTL: "3600"
      APACHE_HOST_PORT: "80"
      APACHE_HTTPS_PORT: "443"
      SERVER_NAME: "unified.example.com"
      SERVER_ADMIN: "admin@unified.example.com"
      APACHE_LOG_LEVEL: "warn"
      APP_VERSION: "1.0.0"
      POSTSTACK_ENVIRONMENT: production
      # Network mode configuration (host for production environment - for fail2ban)
      NETWORK_MODE: "host"
      MAIL_USE_HOST_NETWORK: "true"
      APACHE_USE_HOST_NETWORK: "true"
