# Podman Pod specification for Apache web server
# This file demonstrates poststack's environment management with variable substitution
apiVersion: v1
kind: Pod
metadata:
  name: unified-apache-${POSTSTACK_ENVIRONMENT}
  labels:
    app: apache
    environment: ${POSTSTACK_ENVIRONMENT}
    managed-by: poststack
    project: unified
spec:
  initContainers:
  - name: setup-volumes
    image: localhost/unified/apache:latest
    command: ['/bin/bash', '-c']
    args:
    - |
      echo "Setting up Apache volume permissions..."
      mkdir -p /data/logs/apache /etc/apache2/conf.d
      chown -R www-data:certgroup /data/logs/apache
      chmod 755 /data/logs/apache
      chown -R www-data:www-data /etc/apache2/conf.d
      chmod 755 /etc/apache2/conf.d
      echo "Volume setup complete"
    volumeMounts:
    - name: unified-logs
      mountPath: /data/logs
    - name: apache-config
      mountPath: /etc/apache2/conf.d
  containers:
  - name: apache-web
    image: localhost/unified/apache:latest
    ports:
    - containerPort: 80
      hostPort: ${APACHE_HOST_PORT:-8080}
      protocol: TCP
    - containerPort: 443
      hostPort: ${APACHE_HTTPS_PORT:-8443}
      protocol: TCP
    env:
    # Database connection variables (auto-generated from service discovery)
    - name: DATABASE_URL
      value: "${POSTGRES_URL}"
    - name: ENVIRONMENT
      value: "${ENVIRONMENT}"
    - name: DB_HOST
      value: "${POSTGRES_HOST}"
    - name: DB_PORT
      value: "${POSTGRES_PORT}"
    - name: DB_NAME
      value: "${POSTGRES_DATABASE}"
    - name: DB_USER
      value: "${POSTGRES_USER}"
    - name: DB_PASSWORD
      value: "${POSTGRES_PASSWORD}"
    # User-defined environment-specific variables
    - name: LOG_LEVEL
      value: "${LOG_LEVEL}"
    - name: DEBUG_MODE
      value: "${DEBUG_MODE:-false}"
    - name: CACHE_TTL
      value: "${CACHE_TTL:-300}"
    # Apache-specific configuration
    - name: APACHE_SERVER_NAME
      value: "${SERVER_NAME:-localhost}"
    - name: APACHE_SERVER_ADMIN
      value: "${SERVER_ADMIN:-admin@localhost}"
    - name: APACHE_DOCUMENT_ROOT
      value: "/var/www/unified"
    - name: APACHE_LOG_LEVEL
      value: "${APACHE_LOG_LEVEL:-warn}"
    # Application-specific configuration
    - name: APP_NAME
      value: "Unified Project"
    - name: APP_VERSION
      value: "${APP_VERSION:-dev}"
    volumeMounts:
    - name: unified-logs
      mountPath: /data/logs
    - name: apache-config
      mountPath: /etc/apache2/conf.d
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: unified-logs
    ${VOLUME_UNIFIED_LOGS_TYPE}: ${VOLUME_UNIFIED_LOGS_CONFIG}
  - name: apache-config
    ${VOLUME_APACHE_CONFIG_TYPE}: ${VOLUME_APACHE_CONFIG_CONFIG}
  restartPolicy: Always
