# Podman Pod specification for Apache web server
# This file demonstrates poststack's environment management with variable substitution
apiVersion: v1
kind: Pod
metadata:
  name: unified-apache-${POSTSTACK_ENVIRONMENT}
  labels:
    app: apache
    environment: ${POSTSTACK_ENVIRONMENT}
    managed-by: poststack
    project: unified
spec:
  containers:
  - name: apache-web
    image: localhost/unified/apache:latest
    ports:
    - containerPort: 80
      hostPort: ${APACHE_HOST_PORT:-8080}
      protocol: TCP
    - containerPort: 443
      hostPort: ${APACHE_HTTPS_PORT:-8443}
      protocol: TCP
    env:
    # Poststack automatically provides these database variables
    - name: DATABASE_URL
      value: "${POSTSTACK_DATABASE_URL}"
    - name: POSTSTACK_ENVIRONMENT
      value: "${POSTSTACK_ENVIRONMENT}"
    - name: DB_HOST
      value: "${POSTSTACK_DB_HOST}"
    - name: DB_PORT
      value: "${POSTSTACK_DB_PORT}"
    - name: DB_NAME
      value: "${POSTSTACK_DB_NAME}"
    - name: DB_USER
      value: "${POSTSTACK_DB_USER}"
    - name: DB_PASSWORD
      value: "${POSTSTACK_DB_PASSWORD}"
    # User-defined environment-specific variables
    - name: LOG_LEVEL
      value: "${LOG_LEVEL}"
    - name: DEBUG_MODE
      value: "${DEBUG_MODE:-false}"
    - name: CACHE_TTL
      value: "${CACHE_TTL:-300}"
    # Apache-specific configuration
    - name: APACHE_SERVER_NAME
      value: "${SERVER_NAME:-localhost}"
    - name: APACHE_SERVER_ADMIN
      value: "${SERVER_ADMIN:-admin@localhost}"
    - name: APACHE_DOCUMENT_ROOT
      value: "/var/www/unified"
    - name: APACHE_LOG_LEVEL
      value: "${APACHE_LOG_LEVEL:-warn}"
    # Application-specific configuration
    - name: APP_NAME
      value: "Unified Project"
    - name: APP_VERSION
      value: "${APP_VERSION:-dev}"
    volumeMounts:
    - name: apache-logs
      mountPath: /var/log/apache2
    - name: apache-config
      mountPath: /etc/apache2/conf.d
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: apache-logs
    emptyDir: {}
  - name: apache-config
    emptyDir: {}
  restartPolicy: Always
