# Dovecot IMAP/POP3 Server Pod
# Simple mail server for testing multi-service deployments
apiVersion: v1
kind: Pod
metadata:
  name: unified-dovecot-${ENVIRONMENT}
  labels:
    app: dovecot
    environment: ${ENVIRONMENT}
    managed-by: poststack
    project: unified
    component: mail
spec:
  containers:
  - name: dovecot
    image: dovecot/dovecot:latest
    ports:
    - containerPort: 143
      hostPort: ${IMAP_PORT:-1143}
      protocol: TCP
    - containerPort: 993
      hostPort: ${IMAPS_PORT:-1993}
      protocol: TCP
    - containerPort: 110
      hostPort: ${POP3_PORT:-1110}
      protocol: TCP
    - containerPort: 995
      hostPort: ${POP3S_PORT:-1995}
      protocol: TCP
    env:
    # Basic dovecot configuration
    - name: DOVECOT_HOSTNAME
      value: "${MAIL_HOSTNAME:-mail.unified.local}"
    - name: DOVECOT_DOMAIN
      value: "${MAIL_DOMAIN:-unified.local}"

    # Database connection for user authentication
    - name: DATABASE_URL
      value: "postgresql://${DB_USER}:${DB_PASSWORD}@host.containers.internal:${DB_PORT}/${DB_NAME}"
    - name: DB_HOST
      value: "host.containers.internal"
    - name: DB_PORT
      value: "${DB_PORT}"
    - name: DB_NAME
      value: "${DB_NAME}"
    - name: DB_USER
      value: "${DB_USER}"
    - name: DB_PASSWORD
      value: "${DB_PASSWORD}"

    # Environment info
    - name: ENVIRONMENT
      value: "${ENVIRONMENT}"
    - name: LOG_LEVEL
      value: "${LOG_LEVEL:-info}"

    volumeMounts:
    - name: dovecot-mail
      mountPath: /var/mail
    - name: dovecot-config
      mountPath: /etc/dovecot/conf.d
    - name: dovecot-logs
      mountPath: /var/log/dovecot

    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "200m"

    livenessProbe:
      tcpSocket:
        port: 143
      initialDelaySeconds: 30
      periodSeconds: 10

    readinessProbe:
      tcpSocket:
        port: 143
      initialDelaySeconds: 5
      periodSeconds: 5

  volumes:
  - name: dovecot-mail
    ${VOLUME_DOVECOT_MAIL_TYPE:-emptyDir}: ${VOLUME_DOVECOT_MAIL_CONFIG:-{}}
  - name: dovecot-config
    ${VOLUME_DOVECOT_CONFIG_TYPE:-emptyDir}: ${VOLUME_DOVECOT_CONFIG_CONFIG:-{}}
  - name: dovecot-logs
    ${VOLUME_DOVECOT_LOGS_TYPE:-emptyDir}: ${VOLUME_DOVECOT_LOGS_CONFIG:-{}}

  restartPolicy: Always

# Configuration Notes:
#
# This is a simple dovecot deployment for testing multi-service functionality.
# In a real deployment, you would:
# 1. Configure proper SSL certificates
# 2. Set up user authentication against the unified schema
# 3. Configure mail storage and quotas
# 4. Set up proper security policies
#
# Variables:
# - MAIL_HOSTNAME: Hostname for the mail server
# - MAIL_DOMAIN: Domain for email addresses
# - IMAP_PORT: Host port for IMAP (default: 1143)
# - IMAPS_PORT: Host port for IMAPS (default: 1993)
# - POP3_PORT: Host port for POP3 (default: 1110)
# - POP3S_PORT: Host port for POP3S (default: 1995)
